spring.application.name=quan_ly_lop_hoc

# Cấu hình database
spring.datasource.url=jdbc:mysql://localhost:3306/quanlylophoc?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=13112004yen.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Cấu hình JWT
jwt.privateKey=4subtdpFMN1SV+tzwCWffjlNapmaS2U4FnS6jawgFE8=

gemini.api-key=AIzaSyDnrxajBTkyxssDm-7J1Lq5_4yet_U63JQ
gemini.api-url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
